comments.php

Visually it is not a good idea to show comments for pages and posts on the home page or in a category/archive

Display comments only on pages and posts

---

.gitignore

Including this in the repository kind of defeats the purpose of bower doesn't it?

Ignore bower_components

---

comments.php

This code should correct comment.php I assume that /library/ foundation.php is does not need to be re-pulled?

Fix for comments.php

---

library/foundation.php

See: https://wordpress.org/support/topic/url-problem-038-replaces-and-breaks-the-navigation-1

Fix to URL Problem : #038; replaces & and breaks the navigation

---

Gruntfile.js
package.json

I found myself adding these two features every time I clone the upstream repository for my themes, so I figured a pull request would be appreciated by someone.
I work in a local environment with vagrant and livereload is very handy and fast, but somebody may not like livereload on php file changes. Do as you like and add what you want the way you want ;)
Livereload needs a [chrome/firefox extension](https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei)  to work.

Gruntfile with task time tracking and livereload

---

functions.php
library/navigation.php
library/offcanvas-walker.php

Created a new menu-walker for the off-canvas menu, so this now supports multi-level. Next to that, the divider is removed from it: the off-canvas menu doesn't use dividers that way.
See the issue: https://github.com/olefredrik/FoundationPress/issues/248

Multi-level off-canvas menu

---

header.php
library/enqueue-scripts.php

Instead of inserting the stylesheet directly into the header, shouldn't it be queued up like everything else for WordPress to handle at the right time?

Enqueue Main Stylesheet Using wp_enqueue_style For WP Coding Standards

---

README.md
comments.php
footer.php
header.php
hero.php
index.php
library/cleanup.php
library/foundation.php
library/menu-walker.php
library/navigation.php
library/offcanvas-walker.php
page-sidebar-left.php
page.php
search.php
searchform.php
sidebar-left.php
sidebar.php
single.php
woocommerce.php

Also fixed a couple “yoda condition” issues to make unit testing pass.

Updated Action Hooks and Classes for Wordpress Coding Standards

---

comments.php

Improved Method to Check For Direct Access to a File

---

README.md
package.json

I removed the need for global installation of Grunt and Bower.
Basically it's working the same as before. :)

removed global dependency of bower and grunt - #274

---

library/navigation.php

Adapted the breadcrumb solution by thewebtaylor (http://thewebtaylor.com/articles/wordpress-creating-breadcrumbs-without-a-plugin) for FoundationPress

Breadcrumb helper function

---

library/navigation.php

For the single page view the separator class would be shown even if the $separatorclass was false

Added missing check for $separatorclass for single pages

---

library/cleanup.php

In the current configuration FoundationPress is displaying error messages on production websites that have WP_DEBUG set to false. This corrects the issue.

Displays XML error messages on production website

---

.gitignore
composer.json
composer.lock

Let's support composer installers for multi-framework support in wordpress.
By doing so, we have the ability to define a custom themes folder and bring this
as a dependency to build upon. This also makes it easier on
build/deploy processes where we don't have to worry about controlling a parent
theme folder that is being maintained by someone else.
For more info: https://github.com/composer/installers

Add composer file for wordpress-theme install

---

header.php
library/navigation.php
library/offcanvas-walker.php
parts/off-canvas-menu.php

Added the possibility to show the off_canvas navigation on the right side. Before it was hardcoded to the left, now a global variable can be used to easily switch between the two.
I am not sure what the philosophy of FoundationPress is concerning configuration parameters, probably there is a different way you do this?
Right now one single word has to be changed to switch the nav from the left to the right, this can be set in the header.php and be overridden in the off_canvas parts file.

Added the possibility to show the off_canvas navigation on the right side

---

footer.php
functions.php
header.php
library/custom-nav.php
parts/top-bar.php
scss/site/_topbar.scss

This pull request allows the user to select the type of mobile menu
they want - Topbar or Offcanvas - in the theme customizer.
header.php
Selectively output the code needed for an off-canvas menu. If the
customizer setting is offcanvas, that code will be output. I also fixed
what appears to be a bug introduced in the last merge. The
$GLOBALS['offcanvasposition'] was not being echoed when called in the
template.
footer.php
Selectively output the code needed for an off-canvas menu.
library/custom-nav.php
A new file creating the customizer options. also added a filter to add
“offcanvas” or “topbar” classes to the body tag to help with CSS
styles.
functions.php
calling custom-nav.php
parts/top-bar.php
added in the needed <li> for the mobile hamburger menu
scss/site/_topbar.scss
hiding …

Add Customizer Option for Topbar or Offcanvas Mobile Menu

---

library/cleanup.php

The current image match only matches XHTML-style image tags with /> and also over-globs e.g. <img>foo<img/>, catching non-tag elements between tags. This regex corrects all that.

Better pattern match for images to rebuild

---

library/cleanup.php

Fully implement [recommended support](http://docs.woothemes.com/document/third-party-custom-theme-compatibility/) for WooCommerce by declaring FoundationPress content wrappers as WooCommerce wrappers.

Add WooCommerce support

---

library/theme-support.php

Declare support to remove warning message from WooCommerce

Declare WooCommerce support

---

parts/off-canvas-menu.php

because the correct side was not set when calling 'foundationpress_mobile_off_canvas' (therefore the side always defaulted to 'left')
This prevented second level menus from being displayed correctly.

Fixed: The off-canvas mobile menu was not working correctly

---

library/enqueue-scripts.php

Since the scripts are being enqueued in the same function they are registered, there is no need to register them. wp_enqueue_script is all that is needed.

Changed wp_register_script to wp_enqueue_script

---

footer.php
header.php
library/custom-nav.php

When we just install the theme without changing the mobile
layout and menu position in the customizer, mobile menu layout
and position theme mods return false.
Added handling for this so that when the mobile menu layout is
false, the off canvas will be shown; when the mobile menu position is
false, the left position will be used.

Fix out-of-the-box behavior of mobile layout

---

Gruntfile.js
package.json

If interested, I added grunt-browser-sync to FoundationPress. To use, just open the Gruntfile and fill in the host in the proxy field of the browser-sync task. Running the default task will start the browser-sync and watch tasks.

Added grunt-browser-sync

---

library/cleanup.php

Definitely up for a debate on this one, but I think the image size is worth preserving within the image tag for styling purposes. It really doesn't add very much bulk at all, and doesn't cause any responsive conflicts. I also took the liberty of simplifying the function a little bit by simply checking for the "align" and "size" prefix, rather than having a static array of entries. Should prove to be a little more dynamic that way.

Added Size Class Back Into Image Tag Within Content Body

---

library/cleanup.php

CDNs use version numbers to deliver new assets. When version number does not
exist, the asset is treated as the same and therefore must be flushed. Flushing
can be an issue because it creates greater responsibility in having to manage
clearing assets. It would be far easier for us to use version  as default
to offer support to CDNs
A starting theme should not make the assumption that the version of assets is not
needed.

Remove wp versions filter to support cdn caching

---

gulpfile.js
package.json

Added the package task, "use strict", and a comment to tell JS-Lint that the gulpfile is a node.js file.

Gulp package task added

---

parts/featured-image.php

I made a small change (closed the php tag and got the images with echo) - it is easier to understand the code this way.

Made it easier to understand

---

assets/scss/foundation.scss
gulpfile.js

Individual components should all be imported in one line through  `@import foundation`. This just loads the mixins for the components and does not add any CSS. When you `@include` the individual components is when CSS is added so those are the only items that need to be commented out if you want to exclude them.
Look at how the Foundation Zurb Template does it for reference: https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/scss/app.scss
Here's a discussion on this: https://github.com/zurb/foundation-sites-6/issues/20#issue-108416205

Improved foundation.scss file

---

functions.php
library/sticky-posts.php

Changed WP sticky post class to .wp-sticky

---

.gitignore
README.md
gulpfile.js
package.json

We can now run the WPCS Checks before we commit! YAY :)
Read the Readme with regards on how to install everything and get it going, but it should be pretty straightforward and quick to do! Please I need some people to test this out before it gets merged. There are to many environmental variables to guarantee that this will work on everyones system right out of the gate, so I want to know if it works for you.

Added Wordpress Coding Standards Sniffs to Gulp

---

gulpfile.js
package.json

Hi, I've added the gulp module **js-hint** to package.json and then added a task **'lint'** to gulpfile.js so that any custom javascript files are run through jshint.  Hope this is useful.  Please review.

add jshint to package and lint task to gulpfile on watch and build

---

gulpfile.js
library/navigation.php
package.json

Fixes: https://github.com/olefredrik/FoundationPress/issues/680

Added gulp clean tasks

---

gulpfile.js

gulpfile.js has been added to the ignored files of the package task instead of Gruntfile.js

Wrong file name

---

library/sticky-posts.php

The `wp-sticky` class was being added to all posts because there was no conditional in place.

Sticky posts bugfix

---

gulpfile.js

Motion ui currently has a missing semicolon at the last line. This causes errors when including certain files right after it.
Separate files with \n and ;. Then \n is useful when the last line is a // comment

Separate javascript files with semi-colon when concatenating

---

assets/scss/modules/_navigation.scss

Right now the line `ul#menu-main-menu` only targets the specific WordPress menu named `main-menu`. Shouldn't it target ALL menus placed in offcanvas?

Change off-canvas menu height to affect all menus

---

library/widget-areas.php
searchform.php

The sidebar should be using the correct foundation element "input-group"
instead of columns to display the search form. This fixes a disparity
between the text box and button heights, and makes the field take up the
full sidebar width. This also fixes an extra 15px padding on the sidebar
that shouldn't be there.

fix sidebar search to use input-group

---

assets/scss/global/_settings.scss
library/cleanup.php
library/entry-meta.php
library/navigation.php

Introduce the new color [foundation color palette mixin](https://github.com/zurb/foundation-sites/wiki/Upgrading-to-Foundation-6.2#color-palette) and fix this issue https://github.com/olefredrik/FoundationPress/issues/760

Add the new foundation color palette mixin

---

assets/scss/global/_settings.scss

For comparison here is the `_settings.scss` file in the[ Foundation Sites](https://github.com/zurb/foundation-sites) repo.
https://github.com/zurb/foundation-sites/blob/develop/scss/settings/_settings.scss#L45

Bug fix settings file

---

library/responsive-images.php

Currently the function `foundationpress_adjust_image_sizes_attr` is not factoring in several display variables during the creation of `<img>` tag `sizes` attribute value. I've updated it to take in account the actual size of the image, the gutters, and the current template.

Take 2: Optimize responsive images for 3/4 and full width templates

---

library/navigation.php

This actually seems like a bug in the wordpress rules, but this is causing travis builds to fail.

Add missing argument to fix travis CI build

---

header.php

From WordPress 4.3 onwards, it is recommended that you use the Site Icon feature that is built into WordPress, insteaof creating all the link link tha I just removed. The Site Icon feature can be found by going to Appearance -> Customize and clicking on Site Identity.

remove favicon

---

assets/scss/foundation.scss
assets/scss/modules/_editor-style.scss
library/theme-support.php

Most people have problems because the TinyMCE Editor looks different
then the actual theme. To prevent this, the main CSS file can be included into the TinyMCE Editor.
More Information:
https://codex.wordpress.org/Editor_Style

Add foundation.css as editor styles

---

library/cleanup.php

Wordpress adds a with attribute to every figure tag, breaking the whole
layout if the image width is wider than its conainer.
You can see this here: https://foundationpress.olefredrik.com/posts/post-with-an-image-and-caption
I added a filter to remove the width attribute

Bugfix for figure tag

---

library/navigation.php
library/protocol-relative-theme-assets.php

I see all currently open pull requests are failing the Travis CI build because of these existing errors in `master`. This pull request should address all of those errors.

Fix Travis CI Build Errors

---

archive.php
footer.php
header.php
index.php
library/custom-nav.php
library/foundation.php
library/navigation.php
search.php

Fairly minor changes here, consisting of moving `==` intances to
`===` and moving `else if` instances to `elseif`.
In addition, I've moved the `if`/`elseif` control structure in a few places to the [alternate syntax](http://php.net/manual/en/control-structures.alternative-syntax.php) due
to the presence of HTML.
This is all to fix the [warnings PHPCS were throwing](https://gist.github.com/Leland/13958455550d8e9c234fc688d7e97c33) when ran. There are still warnings that get flagged relating to commented out code in a couple of files, but those are benign and can be ignored.
Fixes #907

Reformat code to fit WP PHPCS standards

---

assets/scss/components/_featured-image.scss
library/responsive-images.php
single.php
template-parts/featured-image.php

Created new images sizes specifically for use with featured images on posts/pages. Image sizes are optimized for display in landscape aspect ratios and for HiDPI displays on `small` and `medium` screen sizes. Also updated the `single.php` post template to use the same full width featured image layout as pages.

Featured image optimization

---

assets/javascript/custom/flex-video.js
assets/javascript/custom/responsive-video.js

"flex-video" classes will be deprecated in favour of the "responsive-embed" class. Also -- there is no longer any Vimeo-specific class within F6. Something like the proposed would be a more future-proof starting point for responsive videos.

Remove to-be deprecated classes from flex-video example

---

gulpfile.js

This is related to [this issue](https://github.com/olefredrik/FoundationPress/issues/922).
Removed Motion UI and What Input from Gulp Copy task since both components are already included in javascript/foundation.js by Gulp JavaScript task.

Clean up Gulp Copy task.

---

header.php

The mobile menu button broke in FoundationPress when using Foundation 6.3.1. The problem is the 'title-bar' needs to have the 'data-responsive-toggle' set to the same ID as the button 'data-toggle' value. Solves #951.

Fix Mobile Menu Button AKA Hamburger

---

package.json

Updating to the latest version of bower seems to have fixed these errors related to `internal\fs`
We've started seeing these fs errors pop up across projects over the past week or two so I assumed this was just a matter of the older version of bower still using it (or something.
Before updating bower, I removed node and npm from my system and reinstalled via homebrew, just to make sure.
`sudo rm -rf /usr/local/lib/node_modules`
`sudo rm -rf /usr/local/lib/node_modules`
`brew uninstall node`
`brew install node`
`npm install -g npm`
node v7.6.0   
npm v4.3.0
After that I was still getting errors that look they're coming from bower. I updated bower in the project and everything worked.
Here's what the output looked like before updating bower.
```
> foundationpress@2.9.0 postinstall …
```

update bower version

---

assets/javascript/custom/joyride-demo.js
assets/javascript/custom/responsive-video.js
assets/javascript/custom/stickyfooter.js
library/foundation.php

Moved the Foundation responsive video functionality from the frontend in JS to the backend in PHP. Expanded the support from just YouTube and Vimeo to all WP embed supported video sites. Also, now it supports both 4:3 and 16:9 videos by only adding the `.widescreen` class when needed. 
**To test out the new functionality, make a post/page with the following content.**
_(Note the YouTube videos in both 4:3 and 16:9 aspect ratio.)_
```html
<h2>Responsive Video Demo</h2>
<h2>College Humor</h2>
http://www.collegehumor.com/video/7043367/awkward-at-parties-horror-movie-with-allison-williams-and-lil-rel
<h2>Daily Motion</h2>
http://www.dailymotion.com/video/x5ewmxr_bbc-dad-says-he-s-flattered-by-response-to-viral-interview_news
<h2>Funny or Die</h2> …
```

Clean Up JS and Expand Responsive Video Functionality

---

library/foundation.php

Minor Video Embed Optimization

---

search.php

Removed hard coded css classes 'small-12 large-8 columns' which are a legacy feature from older versions.
Using the 'main-content' css class the page inherits the same behaviour as the default page.
Changed page header to h1 and placed inside a header tag similar to 'page.php'.
The purpose of these changes was to have the search page follow the same behaviour as the other pages in the template.

Changed search template to match default page mark up

---

assets/scss/modules/_navigation.scss

The hard-coded height was breaking nav bar items that consist of multiple lines. (In some languages, this is likely to happen.) I don't see any reason to do it in the first place or am I missing something?

fix hard-coded height of menu items

---

footer.php
header.php
library/foundation.php
template-parts/mobile-off-canvas.php

Fixes issue #977. See the extended commit messages for details.

Fix Off-Canvas Menu Bug

---

library/navigation.php

Using the raw search terms as a class, despite being escaped, is a bad idea. Depending on which search terms are being used (and, more importantly, if there are spaces in the search query), these may potentially include existing CSS class keywords which can cause style/layout issues on the page.
`i.e, a search for "small blue product" -> <li class="current item-current-small blue product">, which is not good.`

Remove search query from current breadcrumb class

---

library/navigation.php

Making the nav menu names translatable. The reason for using `esc_html__()` [is explained here](https://wordpress.stackexchange.com/questions/244867/can-someone-explain-the-use-cases-of-esc-html).

Make nav menu names translatable

---

page.php
single.php

Fixed small typo in Edit link in Page and Single that prevent
traduction to work

Fixed Edit link

---

library/navigation.php

On Custom Post Type Archives the breadcrumb currently shows only the "home page".
This additional code will add the custom post type name as current menu item.

CPT Archive Support for FoundationPress Breadcrumb

---

gulpfile.babel.js
library/enqueue-scripts.php

Enqueues jQuery in WordPress insted of loading it with Webpack and makes
the Webpacked Foundation scripts dependant on jQuery.
Issue #1037

Change jQuery loading method

---

src/assets/scss/global/_wp-admin.scss

* adds responsive off-canvas offsets

Prevent wp admin bar from overlapping Foundation menus

---

library/responsive-images.php

Changed regex so it could only start with width or height.

---

library/foundation.php

In the pagination, the current page number was wrapped in an anchor which made it display incorrectly. Also added the `role` and `aria-navigation` attributes to the `ul` as specified in Foundation docs.

Fix pagination

---

page-templates/kitchen-sink.php
src/assets/scss/templates/_kitchen-sink.scss

Fixed kitchen sink grid update

---

library/class-foundationpress-comments.php
library/theme-support.php

Fixes #1066 courtesy of @Makar.

Added text domain to comment awaiting moderation message

---

library/theme-support.php

Fixes #1067, courtesy of @Makar.

Updated editor styles to match new app.css path

---

library/cleanup.php

Remove woocommerce hooks as not needed for the current implementation of woo integration.  This Closes #1082 .

remove woocommerce hooks.

---

gulpfile.babel.js
library/enqueue-scripts.php
package.json

@olefredrik @colin-marshall Hey guys, take your time on this one. Please review as a possible new feature. Cachebusting has been discussed in the past. However, I believe @olefredrik said it needed to be automatic and use hashing.
A few things:
1. It is using gulp_rev as reflected in the package.json . So, please update your installed packages.
2. By default hashing is turned OFF to give users the choice to use or not to use. To test, go to line 27 of the gulp file and change to "true".
3. Hashing will work on the "npm run build" and "npm run dev" commands. It will not on the start command with browsersync. This is by design.
4. I like the manifest.json file split out, but it is possible to combine, which might make the enqueing functions tighter, but I didn't mind it.
I tested this with …

Static Asset Hashing

---

README.md

Related to https://github.com/olefredrik/FoundationPress/pull/1114

Add info about static asset hashing in readme

---

README.md
config-default.yml
gulpfile.babel.js

Moved rev constant to config per suggestion by @colin-marshall on #1114  . Hopefully, this is what you wanted.

Move rev constant to config file

---

library/enqueue-scripts.php
library/theme-support.php

Combine asset path function by @colin-marshall  . Very nifty and much prettier. Pretty pretty. Also added to editor_styles support.

Combine asset path function. Much prettier.

---

library/enqueue-scripts.php

Fix php error in asset_path function

---

.gitignore
README.md
codesniffer.ruleset.xml
config-default.yml
gulpfile.babel.js
package-lock.json
package.json

As discussed in #1127.
Merge #1130 before this one.

Reintroduce WPCS without Travis

---

page-templates/page-full-width.php
src/assets/scss/modules/_content.scss

CSS rules written for `.main-content` in the full-width template will fallback to rules for `.main-content` in the default template. Create a new `.main-content-full-width` class for the full-width template and remove the `.full-width` class from `.main-wrap` to prevent unwanted style collisions.
Resolves #1146.

Change the full-width template class to .main-content-full-width

---

package.json
src/assets/scss/_settings.scss

This updates Foundation for Sites to 6.4.3 in package.json and matches changes in _settings.scss to the Zurb Foundation Template, except for $body-font-family.
Note that some colors and padding was changed, to match Foundation for Sites. If these colors where different by purpose then we need to edit the pull request (or make a new one).
This was discussed in https://github.com/olefredrik/FoundationPress/issues/1152

Update to Foundation for Sites 6.4.3

---

src/assets/scss/_settings.scss

Reverts style changes introduced in #1154 back to FoundationPress norms.
We lost some of the custom FoundationPress style settings in the update as seen in the screenshot below:

Revert style changes in 6.4.3 up-to-date

---

config-default.yml
gulpfile.babel.js

Consistence naming of the folder "images", so pictures will be now compressed in production. The folder "img" doesn't exist by default.

Tiny update gulpfile.babel.js

---

header.php

This removes a single failure in the Lighthouse accessibility audit.
On a sidenote, I decided to leave the `FoundationPress.pot` file alone, even if I was adding a new translatable string due to some issues with POEdit on my side.

Adding aria-label attribute to mobile menu hamburger button

---

config-default.yml

Prevents empty "scss" folder from appearing in /dist on production builds.

Fix asset exclusion globbing pattern

---

404.php
page-templates/front.php
page-templates/kitchen-sink.php
page.php
template-parts/mobile-off-canvas.php
template-parts/mobile-top-bar.php

This branch has improvements over a few files to keep the indenting + code formatting consistent across the theme.
Relates to issue: #1172

Improvements + Consistency updates in code indentation across multiple php files

---

gulpfile.babel.js

Hey guys,
I've been using FP with a slightly modified configuration, similar to the proposed, which offers up some pretty significant optimizations:
-An exclusion added for "node_modules" to the Webpack config to avoid needless transforming on that folder during dev. Small speed bump here.
-JavaScript task broken down into separate build and watch functions. The purpose of this is two fold:
1. Being able to use Webpack's native watcher function (as opposed to watching JS with Gulp). During dev, JS updates are MUCH faster - basically instant.
2. Webpack's native source mapping, I've found, is markedly more useable and speedier than the maps generated by gulp-sourcemap.
The reason behind splitting out the JS watch from the main watch() function is so that they can be run in parallel. …

Optimize JavaScript tasks

---

gulpfile.babel.js

Related to #1202 and #1204.
I have no idea how I didn't see this before, but if you `console.log(webpackConfig)` in the current webpack.watch function, it returns undefined -- meaning no config passed in to the watcher, and no transforms on any .js files, hence the errors referenced above.
This PR moves the config into the scope of the `webpack` object, and adds a bit of sugar/cleanup otherwise. Also -- the 'exclude' option is now set so that the Foundation .js files are always transpiled down to ES5 (as opposed to just in production), as I noticed syntax errors pop up while testing in IE10 and 11 during --dev.

Refine Webpack watch + build functions

---

footer.php
library/widget-areas.php
src/assets/scss/modules/_footer.scss

Change:
- Issue #1180 - Update and fix footer container.
Note: I did not add a background color to ".footer" . I felt you should leave to the dev to decide whether to leave transparent or what have you. The structure is the important thing.

Fix footer container.  #1180

---

gulpfile.babel.js

Relevant issue #1144. Updates the watch task with event listeners on change and unlink events for the php and sass watch tasks.
@Aetles let me know if this is better.

Added path for php and scss file changes/removals to console output.

---

library/custom-nav.php

Closes #1200. One check for a setting for the mobile navigation defaulted to the top bar while another defaulted to off canvas. Switched it so both default to top bar.

Make topbar default if mobile nav setting isn't already defined

---

library/cleanup.php

- This is to fix the  image alignment bug discussed in  #1237.
Note: I believe this function is no longer needed. Currently, the global scss has imgs set to max-width: 100% and Height: auto that makes them responsive by default. I did a test with the default FP template and everything worked as expected. This was a good catch by @jturmelle and useful to have working properly for bloggers.

Fix image alignment bug discussed in #1237.

---

library/enqueue-scripts.php

update jqmigrate to be compatible with jquery version used

---

page.php

Small code cleanup at the page.php while loop.
Makes the code more consistent with other files.
Closes #1246.

Code cleanup while loop page.php

---

gulpfile.babel.js

See issue #1256 - since FP now uses fancy log instead of util.log, the broken log was replaced.

Replace deprecated log call

---

src/assets/scss/modules/_footer.scss

In response to #1251. Not really a bug, but being a little more opinionated and adding a default breakpoint for the widget area "out of the box" may clear up some confusion. It really will depend on what people have for their widgets, so most likely people will always need to tweak.

Add default breakpoint for smaller screen sizes to footer widget area. #1251

---

library/enqueue-scripts.php
package-lock.json

use get_stylesheet_directory_uri to support usage as childtheme

---

gulpfile.babel.js

Watch task to handle SVG files

---

gulpfile.babel.js
package-lock.json
package.json

This PR addresses #1286 and enhances the package by updating `gulp-imagemin`.
Updating `gulp-imagemin` also meant updating `gulpfile.babel.js` to accommodate the current syntax that `gulp-imagemin` now uses. I've included a couple of examples of options that can be configured for each imagemin plugin.

Fix image watcher copying images + reloading browser. Bump gulp-imagemin to 4.1.0.

---

index.php

All default templates with the exception of `index.php` use a container. This adds the container to `index.php` for consistency.
Closes #1298

Add container to index.php to match other default page templates

---

comments.php
library/foundation.php

I cleaned the comments page (replaced the hardcoded comment form with `comment_form()`) template tag) to fix several problems with third party plugins #1291 and I added a comments pagination to support comments on multiple pages #1295
I also removed some unnecessary conditions like the check if the template is loaded on `page()` or `single()`. I compared the comments template to the official comments templte of the twentyseventeen theme. Since the official theme does not include any of this statements I decided to remove them.

Comments template cleaned up and refactored

---

functions.php
gulpfile.babel.js
library/foundation.php
library/gutenberg.php
library/theme-support.php
src/assets/scss/app.scss
src/assets/scss/editor.scss
src/assets/scss/global/_gutenberg.scss

This Pull Request is related to the Issue #1301 
This is the first try of an implementation to a Gutenberg Editor support.
I followed the official gutenberg guidelines for themes
https://wordpress.org/gutenberg/handbook/extensibility/theme-support/
The implementation of the editor styles is inspired from the new [Twenty Nineteen Default Theme](https://github.com/WordPress/twentynineteen)

Gutenberg Support

---

README.md

Before opening a pull request, please make sure to do the following:

Sentence correction

---

package.json

#1341
Since gulpfile.js changed to gulpfile.babel.js the main file within the package.json should change to.

Main file changed to gulpfile.babel.js

---

package-lock.json
package.json

There were 11 vulnerabilities (9 moderate, 2 high)
I fixed them via `npm audit fix` and manual package updates.
I updated 
- gulp-cli
- gulp-imagemin
- sshpk
Dependency of gulp-sass [dev]
Path: `gulp-sass > node-sass > node-gyp > request > http-signature > sshpk`

Dependency updates / Security fixes

---

library/foundation.php

This PR Resolves #1371 
This PR has the following changes:
- Moves `str_replace` and `preg_replace` match patterns to their own arrays.
- Moves `str_replace` and `preg_replace` replacements to their own arrays.
- Numerous calls to `str_replace` and `preg_replace` have been replaced by one call each, with args populated by arrays.
- Numerous match patterns are more concise, so no HTML tags are accidentally replaced.
- Numerous match patterns have been updated to match [Foundation's documented markup](https://foundation.zurb.com/sites/docs/pagination.html).
- Replace `prev_text` and `next_text` with empty strings, as the new markup automatically inserts left/right arrows.
- Wrap pagination output in a `<nav>` element.

Fixes foundationpress_pagination() - Outputs valid HTML, output matches Foundation's docs.

---

src/assets/js/lib/foundation-explicit-pieces.js

Reference #1363 
Fix incorrect filename in src/assets/js/lib/foundation-explicit-pieces.js that cause compile error.

Fix foundation-explicit-pieces.js compile error

---

library/foundation.php

This PR solves issue #1394 .
This PR adds the missing closing LI tag in `library/foundation.php:51`.

Fixes pagination missing closing LI tags
