- library/cleanup.php
- library/enqueue-scripts.php
- library/foundation.php
- library/menu-walker.php
- library/navigation.php
- library/theme-support.php
- library/widget-areas.php
Added !function_exists( for child theme support
Also added FoundationPress_ prefix to some functions to standardise
their name (will help to avoid conflicts with plugins etc).
> Added Child Theme Support

- Gruntfile.js
Start watching for changes on js/custom folder and execute the proper tasks
> Start watching for changes on js/custom folder

- library/cleanup.php
img_unautop incorrectly referenced in conditional as img_unauto.
> Fix function name misspelling:

- library/enqueue-scripts.php
Register CDN-hosted jquery before enqueuing below.
> change enqueue jquery to register jquery

- library/cleanup.php
as mentioned in bug https://github.com/olefredrik/FoundationPress/issues/110
> solve image aligment in posts

- scss/config/_custom-settings.scss
- scss/site/_topbar.scss
https://github.com/olefredrik/FoundationPress/issues/377
> Fix topbar styling bug

- assets/scss/site/_wp-admin.scss
https://github.com/olefredrik/FoundationPress/issues/452
> Fix issue with wpadminbar overlap sticky topbar

- README.md
> Sass not SASS

- README.md
Fix line number mentioned in readme to reflect current gruntfile.
> Update readme: browsersync gruntfile line number

- README.md
Discovering this theme as saved us time and energy in deciding the essential in organizing our theme assets and build tools.
Thanks for all your support!
> Add OffGrid Magazine site to showcase

- gulpfile.js
Forgot to add a conditional so JavaScript was minifying without the production flag.
> Fixed JavaScript minify

- content.php
- page.php
- templates/page-full-width.php
- templates/page-sidebar-left.php
Found a few more duplicate classes related to: https://github.com/olefredrik/FoundationPress/issues/614
> Fixed more instances of duplicate class attributes in templates

- library/navigation.php
Fixes: https://github.com/olefredrik/FoundationPress/issues/627 courtesy of @beniven
> Added missing angle bracket

- gulpfile.js
- parts/mobile-off-canvas.php
- parts/mobile-top-bar.php
https://github.com/olefredrik/FoundationPress/issues/661
> Fix off canvas bug

- composer.json
https://github.com/olefredrik/FoundationPress/issues/659
> FP is based on Foundation 6

- gulpfile.js
- library/enqueue-scripts.php
https://github.com/olefredrik/FoundationPress/issues/669
> Remove this as we use CDN hosted jQuery

- package.json
> npm run package now minifies css & js

- assets/scss/foundation.scss
* @include foundation-global-styles; appears twice
- first under global styles
- second under foundation components
* remove duplicate under foundation components
> Remove duplicate line from foundation.scss

- assets/scss/modules/_navigation.scss
Fix https://github.com/olefredrik/FoundationPress/issues/752
> Fix dropdown menu arrows

- .github/ISSUE_TEMPLATE.md
Due to the number of issues where software versions were the reason something was breaking, I added questions for that. @colin-marshall also suggested adding updated links to CodePen for test cases.
> Updated Issue Template with New Questions

- gulpfile.js
- package.json
- style.css
Autoprefixer should target older Android browsers: https://github.com/olefredrik/FoundationPress/issues/826
https://github.com/DaSchTour/foundation-sites/commit/a767010f9c2dac81ffc62edea5110717933a09ef
> Autoprefixer compability

- assets/scss/modules/_navigation.scss
- page.php
- single.php
the_post_navigation since WP 4.1: https://developer.wordpress.org/reference/functions/the_post_navigation/
edit_post_link for users not displaying WP toolbar
Styles for the_post_navigation
> Introducing the_post_navigation and edit_post_link

- assets/scss/components/_featured-image.scss
- assets/scss/components/_links.scss
- assets/scss/global/_wp-admin.scss
- assets/scss/global/_wp-overrides.scss
- assets/scss/modules/_editor-style.scss
- assets/scss/modules/_footer.scss
- assets/scss/modules/_navigation.scss
- assets/scss/templates/_front.scss
- assets/scss/templates/_kitchen-sink.scss
- assets/scss/templates/_page-default.scss
- assets/scss/templates/_page-full-width.scss
- assets/scss/templates/_single-post.scss
Normalized all of the SCSS files to be more consistent and better match vanilla Foundation.
> Normalize SCSS

- assets/scss/global/_settings.scss
16rem font size in dropdown menu is HUGE.
> Typo in dropdown font size setting

- README.md
- library/foundation.php
> Updated README.md with info on packaging the theme to a zip file

- assets/scss/components/_cards.scss
- assets/scss/foundation.scss
- assets/scss/global/_accessibility.scss
- assets/scss/global/_settings.scss
- assets/scss/modules/_navigation.scss
- assets/scss/templates/_kitchen-sink.scss
- bower.json
- gulpfile.js
- package.json
- page-templates/kitchen-sink.php
- style.css
- template-parts/mobile-off-canvas.php
Update to Foundation v6.3.0  :rocket:
> Foundation v6.3.0

- assets/javascript/custom/joyride-demo.js
- assets/javascript/custom/responsive-video.js
- assets/javascript/custom/stickyfooter.js
> Solve/Avoid JS Conflict by Replacing '$' with 'jQuery'

- .travis.yml
https://github.com/olefredrik/FoundationPress/issues/959
> Update PHP versions to use in Travis CI Build Checks

- .travis.yml
> Add PHP 5.6 and Nightly to Travis CI 

- library/navigation.php
This makes breadcrumbs able to handle any custom taxonomies with any level of nesting.
> Add taxonomies support to breadcrumbs

- package.json
https://github.com/olefredrik/FoundationPress/issues/986
> Update gulp-sourcemaps to latest version

- library/enqueue-scripts.php
- package.json
- src/assets/scss/modules/_footer.scss
- style.css
Minor fix to correctly use the XY-Grid in footer.
> Xy grid in footer

- .github/ISSUE_TEMPLATE.md
- config.yml
- gulpfile.babel.js
- package.json
Removing UnCSS from the project, as this is primarily built to work with static sites and HTML files. It should be possible to make it work with php files as well, but I have not yet seen a solution that works optimally without errors.
> Dependencies

- library/foundation.php
https://github.com/olefredrik/FoundationPress/issues/933
> Active class menu item

- library/enqueue-scripts.php
commented out FontAwesome CDN enqueue line. Enabling given over to developer's preference or need
> de-queue FontAwesome CDN

- package.json
https://github.com/olefredrik/FoundationPress/issues/1048
> Target Foundation version 6.4.1

- page-templates/kitchen-sink.php
- src/assets/scss/templates/_kitchen-sink.scss
> Updated kitchen sink grid to XY Grid

- library/cleanup.php
- library/widget-areas.php
Change from article element to section for widget areas in sidebar and footer. Small spelling correction in cleanup.
> Widget area element change. Small spelling correction.

- package-lock.json
- package.json
Running a newer version of Node/npm and it created a `package-lock.json` file and removed the blank spaces in `package.json`.
According to the [npm docs](https://docs.npmjs.com/files/package-lock.json), `package-lock.json` is intended to be committed into the source repository for a number of reasons.
> package.json updates

- template-parts/check-if-sidebar-exist.php
#1103 Suggest removing this. Not used anymore...? Created confusion for me as I expected it to do something because it was there.
> Remove unused sidebar template part.

- footer.php
- header.php
- page-templates/page-full-width.php
- page-templates/page-sidebar-left.php
- page.php
- search.php
- searchform.php
- sidebar.php
- single.php
- template-parts/content-page.php
- template-parts/content.php
#1097 @olefredrik @colin-marshall I went nutty and removed them all throughout all templates.
> Remove template hooks.

- README.md
> Update README.md to reflect JavaScript changes

- footer.php
https://github.com/olefredrik/FoundationPress/issues/1095
> Remove data attribute for sticky footer

- .gitignore
- README.md
- config-default.yml
- gulpfile.babel.js
- package-lock.json
- package.json
> Reintroduce package task

- README.md
Changing the world for the better using FoundationPress 💪 
Kudos to Brian Douglas
> Add Impeach Trump Now site to the showcase

- 404.php
- archive.php
- footer.php
- header.php
- index.php
- page-templates/kitchen-sink.php
- page-templates/page-full-width.php
- page-templates/page-sidebar-left.php
- page.php
- search.php
- single.php
- src/assets/scss/modules/_content.scss
- woocommerce.php
Resolves https://github.com/olefredrik/FoundationPress/issues/1151
> Separate grid element from container

- package-lock.json
Change:
- Issue #1174 - If FP tracks the file, updated package-lock.json to reflect the update to Foundation.
> Update package-lock.json file with updated Foundation version.

- page.php
- single.php
Related to #1172 
Removed stray ']' on page.php and also updated indentation on single.php.
> Remove stray ‘[‘ and update single.php sidebar indentation

- package-lock.json
- package.json
Fixes build problems arising from incompatible webpack and babel-loader versions. Closes #1192 and #1193. Credit: @alexbohariuc.
> Bumped bablel-loader, webpack, and webpack-stream in package.json

- gulpfile.babel.js
- package-lock.json
- package.json
Closes #1211.
More info: https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
> Replace deprecated gulp-util with ansi-colors and fancy-log

- gulpfile.babel.js
> Remove reference to gutil in gulpfile

- src/assets/scss/app.scss
> Removed underscore from accessibility import in app.scss

- package-lock.json
- Update package-lock file to sync up with package.json .
> Update package-lock.json file to sync up with package.json .

- gulpfile.babel.js
> fix: update webpack exclude rules for Windows compatibility

- README.md
Thanks for your great work on FoundationPress !
> Add La revanche des sites to showcase

- README.md
> Licence Badge Updated

- searchform.php
- Pass accessibility audits
- Aid in assistive technologies
https://github.com/olefredrik/FoundationPress/issues/1307
Before opening a pull request, please make sure to do the following:
> Add aria label to the search form to assist in accessibility

- package-lock.json
Two vulnerabilities in sub packages of gulp-sass fixed.
package: sshpk
Path: gulp-sass > node-sass > request > http-signature > sshpk
```
=== npm audit security report ===
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ sshpk                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-sass [dev]                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-sass > node-sass > node-gyp > request …
```
> vulnerabilities fixed

- header.php
Just tidying up code, remove an extra empty line from `header.php`
> Remove extra line
